apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  stub_status.conf: |
    # Stub status endpoint for Prometheus monitoring
    location /stub_status {
        stub_status on;
        access_log off;
        allow all;
    }