apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-prometheus-exporter
spec:
  template:
    spec:
      containers:
      - name: exporter
        args:
          - --nginx.scrape-uri=http://staging-nginx:80/stub_status