apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  project: infra
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: external-dns
    targetRevision: 8.5.1
    helm:
      values: |
        image:
          registry: registry-1.docker.io
          repository: bitnamilegacy/external-dns
        provider: ovh
        policy: sync
        txtOwnerId: argocd
        domainFilters:
          - example.com
        sources:
          - ingress
        ovh:
          endpoint: ovh-eu
        extraEnv:
          - name: OVH_APPLICATION_KEY
            valueFrom:
              secretKeyRef:
                name: ovh-credentials
                key: applicationKey
          - name: OVH_APPLICATION_SECRET
            valueFrom:
              secretKeyRef:
                name: ovh-credentials
                key: applicationSecret
          - name: OVH_CONSUMER_KEY
            valueFrom:
              secretKeyRef:
                name: ovh-credentials
                key: consumerKey
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
