apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  project: infra
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: external-dns
    targetRevision: 8.5.1
    helm:
      values: |
        image:
          registry: registry-1.docker.io
          repository: bitnamilegacy/external-dns
        provider: ovh
        policy: sync
        txtOwnerId: argocd
        domainFilters:
          - glefer.fr
        sources:
          - ingress
        ovh:
          endpoint: ovh-eu
          secretName: ovh-credentials
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
