apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: infra
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.11.3
    helm:
      values: |
        controller:
          service:
            type: LoadBalancer
            ports:
              http: 80
              https: 443
            targetPorts:
              http: http
              https: https
            annotations:
              # Retirer les annotations AWS pour OVH
              metallb.universe.tf/allow-shared-ip: "ingress-nginx"
          config:
            # Temporairement désactiver HTTP/3 pour debug
            # enable-quic: "true"
            use-http2: "true"
            ssl-protocols: "TLSv1.2 TLSv1.3"
            # Logs pour debug
            error-log-level: "info"
            access-log-params: "buffer=16k flush=5s"
          # Activer les métriques
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
          # Health checks
          readinessProbe:
            httpGet:
              path: "/healthz"
              port: 10254
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: "/healthz"
              port: 10254
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
          # Resources
          resources:
            requests:
              cpu: 100m
              memory: 90Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
