apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core-base
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/glefer-training/infra-gitops.git
        revision: main
        directories:
          - path: core/*
  template:
    metadata:
      name: '{{path.basename}}'
      annotations:
        argocd.argoproj.io/sync-wave: '{{path.basename | regexFind "[0-9]+" | default "0"}}'
    spec:
      project: core
      source:
        repoURL: https://github.com/glefer-training/infra-gitops.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core-overlays
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/glefer-training/infra-gitops.git
        revision: main
        directories:
          - path: core/*/overlays/*
  template:
    metadata:
      name: '{{path[1]}}-{{path.basename}}'
      annotations:
        argocd.argoproj.io/sync-wave: '{{path[1] | regexFind "[0-9]+" | default "0"}}'
    spec:
      project: core
      source:
        repoURL: https://github.com/glefer-training/infra-gitops.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path[1]}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
