apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-prometheus-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-prometheus-exporter
  template:
    metadata:
      labels:
        app: nginx-prometheus-exporter
    spec:
      containers:
      - name: exporter
        image: nginx/nginx-prometheus-exporter:latest
        args:
          - --nginx.scrape-uri=http://nginx:80/stub_status
        ports:
        - containerPort: 9113
