apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-prometheus-exporter-staging
spec:
  project: default
  source:
    repoURL: https://github.com/glefer-training/infra-gitops.git
    path: argocd/apps/20-apps/nginx-prometheus-exporter/overlays/staging
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
