apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-prometheus-exporter-servicemonitor-prod
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/glefer-training/infra-gitops.git
    path: argocd/apps/20-apps/nginx-prometheus-exporter-servicemonitor/overlays/prod
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
